on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: "csu-nl-innovative-ml-apps"
jobs:
  upload_serving_container_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy serving infra
        id: deploy_infra
        run: |
          az deployment group create --resource-group ${{env.RESOURCE_GROUP}} --template-file ./src/alphabrain/iac/fusion_team/container_registry.bicep
      - name: get_container_registry_name
        run: |
          echo "registry=$(az acr list --resource-group ${{env.RESOURCE_GROUP}}  --query "[?contains(name, 'microbrainmlops')][name]" --output tsv)" >> $GITHUB_OUTPUT
      - name: upload containers
        run: |
          ./iac/fusion_team/upload_containter_to_registry.sh ${{steps.get_container_registry_name.outputs.registry}}

  deploy_serving_infrastructure:
    runs-on: ubuntu-latest
    needs: upload_serving_container_image

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy ml serving infra
        id: deploy_infra
        run: |
          az deployment group create --resource-group ${{env.RESOURCE_GROUP}} --template-file ./iac/fusion_team/serving_infrastructure.bicep
      - name: deploy apps infra
        id: deploy_apps_infra
        run: |
          az deployment group create --resource-group ${{env.RESOURCE_GROUP}} --template-file ./iac/fusion_team/main.bicep
